version: '2'
services:
  web:
    build: .
    expose:
      - "5000"
    volumes:
      - .:/code
    networks:
      - midtier
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - midtier
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7080:80"
    networks:
      - midtier
    environment:
      - BACKEND_PORT=5000
      - BALANCE=roundrobin
volumes:
  redis-data:
    driver: local
networks:
  midtier:
    driver: bridge
    